spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/chess   # ggf. auf 3307 ändern
    username: chess
    password: chesspass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

app:
  jwt:
    secret: "1efcbaa0e877f57b6519bb44a461c5131b058560"
    expires-minutes: 60